### ISSUE TITLE
How to go to VR mode?

### ISSUE THREAD

**Issue by wizztjh** [leapmotion/leapjs-rigged-hand#20]
I am trying to integrate leapmotion with oculus which mean that I need to make it compatible with VR with the following code. 

http://blog.leapmotion.com/leap-motion-vr-javascript-a-quick-guide-to-getting-started-webvr/
```
Leap.loopController.use('transform', {
  vr: true
});
```
Can I apply this to leapjs-rigged-hand?

**Comment by codemercenary** [comment]
Not quite sure what the question means.

**Comment by wizztjh** [comment]
@codemercenary just updated the description.

**Comment by pehrlich** [comment]
That `vr: true` flag will only effect the "transform" plugin.  This means the hands will be re-oriented in 3d within 3d space, to handle that the Leap Motion is on a vr headset, rather than the desk.  

What you're probably expecting for full VR is the Stereo view, Optical/lense effect, and position and orientation input.  These are well handled by THREE.js's VREffect and VRControls, along with a WebVR browser. See this example: https://developer.leapmotion.com/gallery/vr-quickstart

**Comment by codemercenary** [comment]
@wizztjh does this answer your question?

**Comment by wizztjh** [comment]
I think so. I will try the vr: true flag.
